<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('districts')->delete();

        \DB::table('districts')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Dhaka',
                'bn_name' => 'ঢাকা',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 12:57:15',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Faridpur',
                'bn_name' => 'ফরিদপুর',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 12:58:09',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Gazipur',
                'bn_name' => 'গাজীপুর',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 12:58:36',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Gopalganj',
                'bn_name' => 'গোপালগঞ্জ',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:27:09',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Jamalpur',
                'bn_name' => 'জামালপুর',
                'division_id' => 8,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 12:59:26',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Kishoreganj',
                'bn_name' => 'কিশোরগঞ্জ',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 12:59:44',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Madaripur',
                'bn_name' => 'মাদারীপুর',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:27:47',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Manikganj',
                'bn_name' => 'মানিকগঞ্জ',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:00:33',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Munshiganj',
                'bn_name' => 'মুন্সিগঞ্জ',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:00:49',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Mymensingh',
                'bn_name' => 'ময়মনসিংহ',
                'division_id' => 8,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:01:53',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Narayanganj',
                'bn_name' => 'নারায়াণগঞ্জ',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:02:17',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Narsingdi',
                'bn_name' => 'নরসিংদী',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:02:30',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Netrokona',
                'bn_name' => 'নেত্রকোনা',
                'division_id' => 8,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 13:02:52',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Rajbari',
                'bn_name' => 'রাজবাড়ি',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:28:31',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Shariatpur',
                'bn_name' => 'শরীয়তপুর',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:29:11',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Sherpur',
                'bn_name' => 'শেরপুর',
                'division_id' => 8,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:30:01',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Tangail',
                'bn_name' => 'টাঙ্গাইল',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:31:55',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Bogra',
                'bn_name' => 'বগুড়া',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:30:37',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Joypurhat',
                'bn_name' => 'জয়পুরহাট',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:30:56',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Naogaon',
                'bn_name' => 'নওগাঁ',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:33:17',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Natore',
                'bn_name' => 'নাটোর',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:33:28',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Nawabganj',
                'bn_name' => 'চাঁপাইনবাবগঞ্জ',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:33:48',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Pabna',
                'bn_name' => 'পাবনা',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:34:36',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Rajshahi',
                'bn_name' => 'রাজশাহী',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:34:50',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Sirajgonj',
                'bn_name' => 'সিরাজগঞ্জ',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:35:11',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Dinajpur',
                'bn_name' => 'দিনাজপুর',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:31:47',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Gaibandha',
                'bn_name' => 'গাইবান্ধা',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:40:06',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Kurigram',
                'bn_name' => 'কুড়িগ্রাম',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:56:22',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Lalmonirhat',
                'bn_name' => 'লালমনিরহাট',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:56:43',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Nilphamari',
                'bn_name' => 'নীলফামারী',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:57:30',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Panchagarh',
                'bn_name' => 'পঞ্চগড়',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:32:21',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Rangpur',
                'bn_name' => 'রংপুর',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:58:08',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Thakurgaon',
                'bn_name' => 'ঠাকুরগাঁও',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:32:45',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Barguna',
                'bn_name' => 'বরগুনা',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:32:58',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Barisal',
                'bn_name' => 'বরিশাল',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:59:01',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Bhola',
                'bn_name' => 'ভোলা',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:59:10',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Jhalokati',
                'bn_name' => 'ঝালকাঠি',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:59:19',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Patuakhali',
                'bn_name' => 'পটুয়াখালী',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:59:31',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Pirojpur',
                'bn_name' => 'পিরোজপুর',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 14:59:47',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Bandarban',
                'bn_name' => 'বান্দরবান',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:00:00',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Brahmanbaria',
                'bn_name' => 'ব্রাহ্মণবাড়িয়া',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:00:12',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Chandpur',
                'bn_name' => 'চাঁদপুর',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:00:34',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'Chittagong',
                'bn_name' => 'চট্টগ্রাম',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:00:56',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'Comilla',
                'bn_name' => 'কুমিল্লা',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:01:04',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'Cox\'s Bazar',
                'bn_name' => 'কক্স বাজার',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:01:30',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'Feni',
                'bn_name' => 'ফেনী',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:03:15',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'Khagrachari',
                'bn_name' => 'খাগড়াছড়ি',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:04:43',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'Lakshmipur',
                'bn_name' => 'লক্ষ্মীপুর',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:04:07',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'Noakhali',
                'bn_name' => 'নোয়াখালী',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:05:29',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'Rangamati',
                'bn_name' => 'রাঙ্গামাটি',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:05:41',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'Habiganj',
                'bn_name' => 'হবিগঞ্জ',
                'division_id' => 7,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:06:13',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'Maulvibazar',
                'bn_name' => 'মৌলভীবাজার',
                'division_id' => 7,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:06:25',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'Sunamganj',
                'bn_name' => 'সুনামগঞ্জ',
                'division_id' => 7,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:06:36',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'Sylhet',
                'bn_name' => 'সিলেট',
                'division_id' => 7,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:06:53',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'name' => 'Bagerhat',
                'bn_name' => 'বাগেরহাট',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:07:09',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'Chuadanga',
                'bn_name' => 'চুয়াডাঙ্গা',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:07:30',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'Jessore',
                'bn_name' => 'যশোর',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:08:04',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'Jhenaidah',
                'bn_name' => 'ঝিনাইদহ',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:08:18',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'Khulna',
                'bn_name' => 'খুলনা',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:08:36',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'Kushtia',
                'bn_name' => 'কুষ্টিয়া',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:08:53',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'Magura',
                'bn_name' => 'মাগুরা',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:09:18',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'Meherpur',
                'bn_name' => 'মেহেরপুর',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:35:35',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'Narail',
                'bn_name' => 'নড়াইল',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:09:42',
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'name' => 'Satkhira',
                'bn_name' => 'সাতক্ষীরা',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-08-18 15:09:53',
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'Dhaka Metro',
                'bn_name' => 'ঢাকা মেট্রো',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:36:04',
                'updated_at' => '2021-08-18 15:11:52',
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'name' => 'Chittagang Metro',
                'bn_name' => 'চট্রগ্রাম মেট্রো',
                'division_id' => 2,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:36:35',
                'updated_at' => '2021-08-18 15:12:20',
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'name' => 'Rajshahi Metro',
                'bn_name' => 'রাজশাহী মেট্রো',
                'division_id' => 5,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:36:50',
                'updated_at' => '2021-08-18 15:12:38',
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'name' => 'Khulna Metro',
                'bn_name' => 'খুলনা মেট্রো',
                'division_id' => 4,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:37:06',
                'updated_at' => '2021-08-18 15:12:51',
                'deleted_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'name' => 'Barishal Metro',
                'bn_name' => 'বরিশাল মেট্রো',
                'division_id' => 1,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:37:24',
                'updated_at' => '2021-08-18 15:13:19',
                'deleted_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'name' => 'Sylhet Metro',
                'bn_name' => 'সিলেট মেট্রো',
                'division_id' => 7,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:37:44',
                'updated_at' => '2021-08-18 15:13:31',
                'deleted_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'name' => 'Rangpur Metro',
                'bn_name' => 'রংপুর মেট্রো',
                'division_id' => 6,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:38:10',
                'updated_at' => '2021-08-18 15:13:50',
                'deleted_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'name' => 'Gazipur Metro',
                'bn_name' => 'গাজীপুর মেট্রো',
                'division_id' => 3,
                'status' => 'Active',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-03 15:38:46',
                'updated_at' => '2021-08-18 15:14:09',
                'deleted_at' => NULL,
            ),
        ));


    }
}
