<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Dashboard',
                'bn_name' => 'ড্যাশবোর্ড',
                'route_name' => 'dashboard',
                'icon' => 'fa fa-home',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:39:06',
                'updated_at' => '2021-07-29 18:30:34',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'role_id' => 1,
                'name' => 'Menu Management',
                'bn_name' => 'মেনু ম্যানেজমেন্ট',
                'route_name' => NULL,
                'icon' => 'fa fa-user',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:41:43',
                'updated_at' => '2021-10-21 11:20:55',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'role_id' => NULL,
                'name' => 'Menu',
                'bn_name' => 'মেনু',
                'route_name' => 'menu.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:42:17',
                'updated_at' => '2021-10-18 10:50:56',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 2,
                'role_id' => NULL,
                'name' => 'Menu Action',
                'bn_name' => 'মেনু একশন',
                'route_name' => 'menu_action.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 12:33:53',
                'updated_at' => '2021-10-17 17:15:04',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Arrangement',
                'bn_name' => 'বিন্যাস',
                'route_name' => NULL,
                'icon' => 'fa fa-compress-arrows-alt',
                'order_by' => 20,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 15:30:35',
                'updated_at' => '2021-07-29 18:27:32',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Division',
                'bn_name' => 'বিভাগ',
                'route_name' => 'division.index',
                'icon' => 'fa fa-disease',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 15:35:24',
                'updated_at' => '2021-07-15 16:10:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Tools',
                'bn_name' => 'টুলস',
                'route_name' => NULL,
                'icon' => 'fas fa-cogs',
                'order_by' => 50,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:07:00',
                'updated_at' => '2021-07-29 18:33:08',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 25,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Content Setup',
                'bn_name' => 'কনটেন্ট সেটাপ',
                'route_name' => 'content.index',
                'icon' => NULL,
                'order_by' => 50,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:11:38',
                'updated_at' => '2021-07-29 18:26:53',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 30,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'District',
                'bn_name' => 'জেলা',
                'route_name' => 'district.index',
                'icon' => 'fa fa-compact-disc',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:12:48',
                'updated_at' => '2021-07-15 16:11:10',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 31,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Upzilla/Thana',
                'bn_name' => 'উপজেলা/থানা',
                'route_name' => 'thana.index',
                'icon' => 'fab fa-discourse',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:12:54',
                'updated_at' => '2021-07-15 16:12:02',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 33,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Fire Station',
                'bn_name' => 'ফায়ার স্টেশন',
                'route_name' => NULL,
                'icon' => 'fa fa-school',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:13:04',
                'updated_at' => '2021-07-15 16:14:05',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 44,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Users',
                'bn_name' => 'ব্যবহারকারী',
                'route_name' => 'user.index',
                'icon' => 'fas fa-user-tag',
                'order_by' => 52,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:18:39',
                'updated_at' => '2021-07-29 18:34:15',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 45,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Roles',
                'bn_name' => 'রোলস',
                'route_name' => 'role.index',
                'icon' => 'fas fa-user-cog',
                'order_by' => 51,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:18:47',
                'updated_at' => '2021-07-29 18:34:28',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 49,
                'parent_id' => 33,
                'role_id' => NULL,
                'name' => 'Fire Station List',
                'bn_name' => 'ফায়ার স্টেশনের লিস্ট',
                'route_name' => 'fire_station.index',
                'icon' => 'fas fa-th-list',
                'order_by' => 51,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:19:36',
                'updated_at' => '2021-07-29 18:19:02',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 63,
                'parent_id' => 33,
                'role_id' => NULL,
                'name' => 'Fire Station Type',
                'bn_name' => 'ফায়ার স্টেশনের শ্রেনী',
                'route_name' => 'fire_station_type.index',
                'icon' => 'fab fa-typo3',
                'order_by' => 50,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-03-01 17:39:18',
                'updated_at' => '2021-07-29 18:19:10',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 74,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Activity Log',
                'bn_name' => 'কার্য বিবরণ',
                'route_name' => 'activity_log.index',
                'icon' => 'fas fa-user-shield',
                'order_by' => 53,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-06-17 17:17:53',
                'updated_at' => '2021-07-29 18:34:42',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 75,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Country',
                'bn_name' => 'দেশ',
                'route_name' => 'country.index',
                'icon' => 'fa fa-flag',
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-03 18:57:51',
                'updated_at' => '2021-07-04 18:45:51',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 94,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Employee',
                'bn_name' => 'কর্মচারী',
                'route_name' => 'employee.index',
                'icon' => 'far fa-user',
                'order_by' => 21,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-02 14:36:31',
                'updated_at' => '2021-08-02 14:36:31',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 95,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Designation',
                'bn_name' => 'উপাধি',
                'route_name' => 'designation.index',
                'icon' => 'fas fa-user-check',
                'order_by' => 28,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-02 16:43:39',
                'updated_at' => '2021-10-18 10:51:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}