<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RolePermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('role_permissions')->delete();
        
        \DB::table('role_permissions')->insert(array (
            0 => 
            array (
                'id' => 2359,
                'role_id' => 1,
                'permission_id' => 1,
                'route_name' => 'dashboard',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            1 => 
            array (
                'id' => 2360,
                'role_id' => 1,
                'permission_id' => 2,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            2 => 
            array (
                'id' => 2361,
                'role_id' => 1,
                'permission_id' => 3,
                'route_name' => 'menu.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            3 => 
            array (
                'id' => 2362,
                'role_id' => 1,
                'permission_id' => 4,
                'route_name' => 'menu_action.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            4 => 
            array (
                'id' => 2363,
                'role_id' => 1,
                'permission_id' => 5,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            5 => 
            array (
                'id' => 2364,
                'role_id' => 1,
                'permission_id' => 6,
                'route_name' => 'division.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            6 => 
            array (
                'id' => 2365,
                'role_id' => 1,
                'permission_id' => 30,
                'route_name' => 'district.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            7 => 
            array (
                'id' => 2366,
                'role_id' => 1,
                'permission_id' => 31,
                'route_name' => 'thana.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            8 => 
            array (
                'id' => 2367,
                'role_id' => 1,
                'permission_id' => 33,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            9 => 
            array (
                'id' => 2368,
                'role_id' => 1,
                'permission_id' => 63,
                'route_name' => 'fire_station_type.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            10 => 
            array (
                'id' => 2369,
                'role_id' => 1,
                'permission_id' => 49,
                'route_name' => 'fire_station.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            11 => 
            array (
                'id' => 2370,
                'role_id' => 1,
                'permission_id' => 75,
                'route_name' => 'country.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            12 => 
            array (
                'id' => 2371,
                'role_id' => 1,
                'permission_id' => 95,
                'route_name' => 'designation.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            13 => 
            array (
                'id' => 2372,
                'role_id' => 1,
                'permission_id' => 10,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            14 => 
            array (
                'id' => 2373,
                'role_id' => 1,
                'permission_id' => 45,
                'route_name' => 'role.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            15 => 
            array (
                'id' => 2374,
                'role_id' => 1,
                'permission_id' => 44,
                'route_name' => 'user.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            16 => 
            array (
                'id' => 2375,
                'role_id' => 1,
                'permission_id' => 74,
                'route_name' => 'activity_log.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            17 => 
            array (
                'id' => 2376,
                'role_id' => 1,
                'permission_id' => 25,
                'route_name' => 'content.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            18 => 
            array (
                'id' => 2377,
                'role_id' => 1,
                'permission_id' => 94,
                'route_name' => 'employee.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            19 => 
            array (
                'id' => 2378,
                'role_id' => 1,
                'permission_id' => 1,
                'route_name' => 'menu.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            20 => 
            array (
                'id' => 2379,
                'role_id' => 1,
                'permission_id' => 243,
                'route_name' => 'menu.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            21 => 
            array (
                'id' => 2380,
                'role_id' => 1,
                'permission_id' => 245,
                'route_name' => 'menu_action.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            22 => 
            array (
                'id' => 2381,
                'role_id' => 1,
                'permission_id' => 246,
                'route_name' => 'menu_action.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            23 => 
            array (
                'id' => 2382,
                'role_id' => 1,
                'permission_id' => 244,
                'route_name' => 'menu_action.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            24 => 
            array (
                'id' => 2383,
                'role_id' => 1,
                'permission_id' => 11,
                'route_name' => 'division.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            25 => 
            array (
                'id' => 2384,
                'role_id' => 1,
                'permission_id' => 12,
                'route_name' => 'division.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            26 => 
            array (
                'id' => 2385,
                'role_id' => 1,
                'permission_id' => 13,
                'route_name' => 'division.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            27 => 
            array (
                'id' => 2386,
                'role_id' => 1,
                'permission_id' => 219,
                'route_name' => 'division.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            28 => 
            array (
                'id' => 2387,
                'role_id' => 1,
                'permission_id' => 220,
                'route_name' => 'division.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            29 => 
            array (
                'id' => 2388,
                'role_id' => 1,
                'permission_id' => 218,
                'route_name' => 'division.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            30 => 
            array (
                'id' => 2389,
                'role_id' => 1,
                'permission_id' => 32,
                'route_name' => 'district.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            31 => 
            array (
                'id' => 2390,
                'role_id' => 1,
                'permission_id' => 33,
                'route_name' => 'district.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            32 => 
            array (
                'id' => 2391,
                'role_id' => 1,
                'permission_id' => 34,
                'route_name' => 'district.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            33 => 
            array (
                'id' => 2392,
                'role_id' => 1,
                'permission_id' => 222,
                'route_name' => 'district.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            34 => 
            array (
                'id' => 2393,
                'role_id' => 1,
                'permission_id' => 223,
                'route_name' => 'district.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            35 => 
            array (
                'id' => 2394,
                'role_id' => 1,
                'permission_id' => 221,
                'route_name' => 'district.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            36 => 
            array (
                'id' => 2395,
                'role_id' => 1,
                'permission_id' => 35,
                'route_name' => 'thana.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            37 => 
            array (
                'id' => 2396,
                'role_id' => 1,
                'permission_id' => 36,
                'route_name' => 'thana.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            38 => 
            array (
                'id' => 2397,
                'role_id' => 1,
                'permission_id' => 37,
                'route_name' => 'thana.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            39 => 
            array (
                'id' => 2398,
                'role_id' => 1,
                'permission_id' => 225,
                'route_name' => 'thana.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            40 => 
            array (
                'id' => 2399,
                'role_id' => 1,
                'permission_id' => 226,
                'route_name' => 'thana.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            41 => 
            array (
                'id' => 2400,
                'role_id' => 1,
                'permission_id' => 224,
                'route_name' => 'thana.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            42 => 
            array (
                'id' => 2401,
                'role_id' => 1,
                'permission_id' => 41,
                'route_name' => 'fire_station_type.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            43 => 
            array (
                'id' => 2402,
                'role_id' => 1,
                'permission_id' => 42,
                'route_name' => 'fire_station_type.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            44 => 
            array (
                'id' => 2403,
                'role_id' => 1,
                'permission_id' => 43,
                'route_name' => 'fire_station_type.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            45 => 
            array (
                'id' => 2404,
                'role_id' => 1,
                'permission_id' => 228,
                'route_name' => 'fire_station_type.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            46 => 
            array (
                'id' => 2405,
                'role_id' => 1,
                'permission_id' => 229,
                'route_name' => 'fire_station_type.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            47 => 
            array (
                'id' => 2406,
                'role_id' => 1,
                'permission_id' => 227,
                'route_name' => 'fire_station_type.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            48 => 
            array (
                'id' => 2407,
                'role_id' => 1,
                'permission_id' => 44,
                'route_name' => 'fire_station.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            49 => 
            array (
                'id' => 2408,
                'role_id' => 1,
                'permission_id' => 45,
                'route_name' => 'fire_station.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            50 => 
            array (
                'id' => 2409,
                'role_id' => 1,
                'permission_id' => 46,
                'route_name' => 'fire_station.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            51 => 
            array (
                'id' => 2410,
                'role_id' => 1,
                'permission_id' => 231,
                'route_name' => 'fire_station.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            52 => 
            array (
                'id' => 2411,
                'role_id' => 1,
                'permission_id' => 232,
                'route_name' => 'fire_station.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            53 => 
            array (
                'id' => 2412,
                'role_id' => 1,
                'permission_id' => 230,
                'route_name' => 'fire_station.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            54 => 
            array (
                'id' => 2413,
                'role_id' => 1,
                'permission_id' => 118,
                'route_name' => 'country.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            55 => 
            array (
                'id' => 2414,
                'role_id' => 1,
                'permission_id' => 119,
                'route_name' => 'country.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            56 => 
            array (
                'id' => 2415,
                'role_id' => 1,
                'permission_id' => 120,
                'route_name' => 'country.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            57 => 
            array (
                'id' => 2416,
                'role_id' => 1,
                'permission_id' => 140,
                'route_name' => 'country.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            58 => 
            array (
                'id' => 2417,
                'role_id' => 1,
                'permission_id' => 133,
                'route_name' => 'country.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            59 => 
            array (
                'id' => 2418,
                'role_id' => 1,
                'permission_id' => 132,
                'route_name' => 'country.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            60 => 
            array (
                'id' => 2419,
                'role_id' => 1,
                'permission_id' => 206,
                'route_name' => 'designation.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            61 => 
            array (
                'id' => 2420,
                'role_id' => 1,
                'permission_id' => 207,
                'route_name' => 'designation.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            62 => 
            array (
                'id' => 2421,
                'role_id' => 1,
                'permission_id' => 208,
                'route_name' => 'designation.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            63 => 
            array (
                'id' => 2422,
                'role_id' => 1,
                'permission_id' => 210,
                'route_name' => 'designation.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            64 => 
            array (
                'id' => 2423,
                'role_id' => 1,
                'permission_id' => 211,
                'route_name' => 'designation.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            65 => 
            array (
                'id' => 2424,
                'role_id' => 1,
                'permission_id' => 209,
                'route_name' => 'designation.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            66 => 
            array (
                'id' => 2425,
                'role_id' => 1,
                'permission_id' => 2,
                'route_name' => 'role.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            67 => 
            array (
                'id' => 2426,
                'role_id' => 1,
                'permission_id' => 3,
                'route_name' => 'role.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            68 => 
            array (
                'id' => 2427,
                'role_id' => 1,
                'permission_id' => 69,
                'route_name' => 'role.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            69 => 
            array (
                'id' => 2428,
                'role_id' => 1,
                'permission_id' => 4,
                'route_name' => 'role.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            70 => 
            array (
                'id' => 2429,
                'role_id' => 1,
                'permission_id' => 216,
                'route_name' => 'role.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            71 => 
            array (
                'id' => 2430,
                'role_id' => 1,
                'permission_id' => 217,
                'route_name' => 'role.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            72 => 
            array (
                'id' => 2431,
                'role_id' => 1,
                'permission_id' => 215,
                'route_name' => 'role.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            73 => 
            array (
                'id' => 2432,
                'role_id' => 1,
                'permission_id' => 14,
                'route_name' => 'user.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            74 => 
            array (
                'id' => 2433,
                'role_id' => 1,
                'permission_id' => 15,
                'route_name' => 'user.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            75 => 
            array (
                'id' => 2434,
                'role_id' => 1,
                'permission_id' => 117,
                'route_name' => 'user.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            76 => 
            array (
                'id' => 2435,
                'role_id' => 1,
                'permission_id' => 16,
                'route_name' => 'user.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            77 => 
            array (
                'id' => 2436,
                'role_id' => 1,
                'permission_id' => 213,
                'route_name' => 'user.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            78 => 
            array (
                'id' => 2437,
                'role_id' => 1,
                'permission_id' => 214,
                'route_name' => 'user.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            79 => 
            array (
                'id' => 2438,
                'role_id' => 1,
                'permission_id' => 212,
                'route_name' => 'user.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            80 => 
            array (
                'id' => 2439,
                'role_id' => 1,
                'permission_id' => 114,
                'route_name' => 'activity_log.show',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            81 => 
            array (
                'id' => 2440,
                'role_id' => 1,
                'permission_id' => 234,
                'route_name' => 'activity_log.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            82 => 
            array (
                'id' => 2441,
                'role_id' => 1,
                'permission_id' => 235,
                'route_name' => 'activity_log.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            83 => 
            array (
                'id' => 2442,
                'role_id' => 1,
                'permission_id' => 233,
                'route_name' => 'activity_log.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            84 => 
            array (
                'id' => 2443,
                'role_id' => 1,
                'permission_id' => 66,
                'route_name' => 'content.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            85 => 
            array (
                'id' => 2444,
                'role_id' => 1,
                'permission_id' => 67,
                'route_name' => 'content.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            86 => 
            array (
                'id' => 2445,
                'role_id' => 1,
                'permission_id' => 68,
                'route_name' => 'content.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            87 => 
            array (
                'id' => 2446,
                'role_id' => 1,
                'permission_id' => 237,
                'route_name' => 'content.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            88 => 
            array (
                'id' => 2447,
                'role_id' => 1,
                'permission_id' => 238,
                'route_name' => 'content.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            89 => 
            array (
                'id' => 2448,
                'role_id' => 1,
                'permission_id' => 236,
                'route_name' => 'content.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            90 => 
            array (
                'id' => 2449,
                'role_id' => 1,
                'permission_id' => 199,
                'route_name' => 'employee.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            91 => 
            array (
                'id' => 2450,
                'role_id' => 1,
                'permission_id' => 200,
                'route_name' => 'employee.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            92 => 
            array (
                'id' => 2451,
                'role_id' => 1,
                'permission_id' => 202,
                'route_name' => 'employee.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            93 => 
            array (
                'id' => 2452,
                'role_id' => 1,
                'permission_id' => 204,
                'route_name' => 'employee.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            94 => 
            array (
                'id' => 2453,
                'role_id' => 1,
                'permission_id' => 205,
                'route_name' => 'employee.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            95 => 
            array (
                'id' => 2454,
                'role_id' => 1,
                'permission_id' => 203,
                'route_name' => 'employee.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            96 => 
            array (
                'id' => 2455,
                'role_id' => 2,
                'permission_id' => 1,
                'route_name' => 'dashboard',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            97 => 
            array (
                'id' => 2456,
                'role_id' => 2,
                'permission_id' => 5,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            98 => 
            array (
                'id' => 2457,
                'role_id' => 2,
                'permission_id' => 6,
                'route_name' => 'division.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            99 => 
            array (
                'id' => 2458,
                'role_id' => 2,
                'permission_id' => 30,
                'route_name' => 'district.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            100 => 
            array (
                'id' => 2459,
                'role_id' => 2,
                'permission_id' => 31,
                'route_name' => 'thana.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            101 => 
            array (
                'id' => 2460,
                'role_id' => 2,
                'permission_id' => 33,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            102 => 
            array (
                'id' => 2461,
                'role_id' => 2,
                'permission_id' => 63,
                'route_name' => 'fire_station_type.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            103 => 
            array (
                'id' => 2462,
                'role_id' => 2,
                'permission_id' => 49,
                'route_name' => 'fire_station.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            104 => 
            array (
                'id' => 2463,
                'role_id' => 2,
                'permission_id' => 75,
                'route_name' => 'country.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            105 => 
            array (
                'id' => 2464,
                'role_id' => 2,
                'permission_id' => 95,
                'route_name' => 'designation.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            106 => 
            array (
                'id' => 2465,
                'role_id' => 2,
                'permission_id' => 10,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            107 => 
            array (
                'id' => 2466,
                'role_id' => 2,
                'permission_id' => 45,
                'route_name' => 'role.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            108 => 
            array (
                'id' => 2467,
                'role_id' => 2,
                'permission_id' => 44,
                'route_name' => 'user.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            109 => 
            array (
                'id' => 2468,
                'role_id' => 2,
                'permission_id' => 74,
                'route_name' => 'activity_log.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            110 => 
            array (
                'id' => 2469,
                'role_id' => 2,
                'permission_id' => 25,
                'route_name' => 'content.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            111 => 
            array (
                'id' => 2470,
                'role_id' => 2,
                'permission_id' => 94,
                'route_name' => 'employee.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            112 => 
            array (
                'id' => 2471,
                'role_id' => 2,
                'permission_id' => 11,
                'route_name' => 'division.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            113 => 
            array (
                'id' => 2472,
                'role_id' => 2,
                'permission_id' => 12,
                'route_name' => 'division.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            114 => 
            array (
                'id' => 2473,
                'role_id' => 2,
                'permission_id' => 13,
                'route_name' => 'division.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            115 => 
            array (
                'id' => 2474,
                'role_id' => 2,
                'permission_id' => 219,
                'route_name' => 'division.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            116 => 
            array (
                'id' => 2475,
                'role_id' => 2,
                'permission_id' => 220,
                'route_name' => 'division.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            117 => 
            array (
                'id' => 2476,
                'role_id' => 2,
                'permission_id' => 218,
                'route_name' => 'division.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            118 => 
            array (
                'id' => 2477,
                'role_id' => 2,
                'permission_id' => 32,
                'route_name' => 'district.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            119 => 
            array (
                'id' => 2478,
                'role_id' => 2,
                'permission_id' => 33,
                'route_name' => 'district.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            120 => 
            array (
                'id' => 2479,
                'role_id' => 2,
                'permission_id' => 34,
                'route_name' => 'district.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            121 => 
            array (
                'id' => 2480,
                'role_id' => 2,
                'permission_id' => 222,
                'route_name' => 'district.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            122 => 
            array (
                'id' => 2481,
                'role_id' => 2,
                'permission_id' => 223,
                'route_name' => 'district.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            123 => 
            array (
                'id' => 2482,
                'role_id' => 2,
                'permission_id' => 221,
                'route_name' => 'district.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            124 => 
            array (
                'id' => 2483,
                'role_id' => 2,
                'permission_id' => 35,
                'route_name' => 'thana.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            125 => 
            array (
                'id' => 2484,
                'role_id' => 2,
                'permission_id' => 36,
                'route_name' => 'thana.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            126 => 
            array (
                'id' => 2485,
                'role_id' => 2,
                'permission_id' => 37,
                'route_name' => 'thana.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            127 => 
            array (
                'id' => 2486,
                'role_id' => 2,
                'permission_id' => 225,
                'route_name' => 'thana.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            128 => 
            array (
                'id' => 2487,
                'role_id' => 2,
                'permission_id' => 226,
                'route_name' => 'thana.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            129 => 
            array (
                'id' => 2488,
                'role_id' => 2,
                'permission_id' => 224,
                'route_name' => 'thana.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            130 => 
            array (
                'id' => 2489,
                'role_id' => 2,
                'permission_id' => 41,
                'route_name' => 'fire_station_type.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            131 => 
            array (
                'id' => 2490,
                'role_id' => 2,
                'permission_id' => 42,
                'route_name' => 'fire_station_type.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            132 => 
            array (
                'id' => 2491,
                'role_id' => 2,
                'permission_id' => 43,
                'route_name' => 'fire_station_type.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            133 => 
            array (
                'id' => 2492,
                'role_id' => 2,
                'permission_id' => 228,
                'route_name' => 'fire_station_type.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            134 => 
            array (
                'id' => 2493,
                'role_id' => 2,
                'permission_id' => 229,
                'route_name' => 'fire_station_type.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            135 => 
            array (
                'id' => 2494,
                'role_id' => 2,
                'permission_id' => 227,
                'route_name' => 'fire_station_type.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            136 => 
            array (
                'id' => 2495,
                'role_id' => 2,
                'permission_id' => 44,
                'route_name' => 'fire_station.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            137 => 
            array (
                'id' => 2496,
                'role_id' => 2,
                'permission_id' => 45,
                'route_name' => 'fire_station.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            138 => 
            array (
                'id' => 2497,
                'role_id' => 2,
                'permission_id' => 46,
                'route_name' => 'fire_station.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            139 => 
            array (
                'id' => 2498,
                'role_id' => 2,
                'permission_id' => 231,
                'route_name' => 'fire_station.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            140 => 
            array (
                'id' => 2499,
                'role_id' => 2,
                'permission_id' => 232,
                'route_name' => 'fire_station.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            141 => 
            array (
                'id' => 2500,
                'role_id' => 2,
                'permission_id' => 230,
                'route_name' => 'fire_station.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            142 => 
            array (
                'id' => 2501,
                'role_id' => 2,
                'permission_id' => 118,
                'route_name' => 'country.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            143 => 
            array (
                'id' => 2502,
                'role_id' => 2,
                'permission_id' => 119,
                'route_name' => 'country.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            144 => 
            array (
                'id' => 2503,
                'role_id' => 2,
                'permission_id' => 120,
                'route_name' => 'country.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            145 => 
            array (
                'id' => 2504,
                'role_id' => 2,
                'permission_id' => 140,
                'route_name' => 'country.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            146 => 
            array (
                'id' => 2505,
                'role_id' => 2,
                'permission_id' => 133,
                'route_name' => 'country.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            147 => 
            array (
                'id' => 2506,
                'role_id' => 2,
                'permission_id' => 132,
                'route_name' => 'country.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            148 => 
            array (
                'id' => 2507,
                'role_id' => 2,
                'permission_id' => 206,
                'route_name' => 'designation.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            149 => 
            array (
                'id' => 2508,
                'role_id' => 2,
                'permission_id' => 207,
                'route_name' => 'designation.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            150 => 
            array (
                'id' => 2509,
                'role_id' => 2,
                'permission_id' => 208,
                'route_name' => 'designation.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            151 => 
            array (
                'id' => 2510,
                'role_id' => 2,
                'permission_id' => 210,
                'route_name' => 'designation.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            152 => 
            array (
                'id' => 2511,
                'role_id' => 2,
                'permission_id' => 211,
                'route_name' => 'designation.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            153 => 
            array (
                'id' => 2512,
                'role_id' => 2,
                'permission_id' => 209,
                'route_name' => 'designation.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            154 => 
            array (
                'id' => 2513,
                'role_id' => 2,
                'permission_id' => 2,
                'route_name' => 'role.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            155 => 
            array (
                'id' => 2514,
                'role_id' => 2,
                'permission_id' => 3,
                'route_name' => 'role.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            156 => 
            array (
                'id' => 2515,
                'role_id' => 2,
                'permission_id' => 69,
                'route_name' => 'role.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            157 => 
            array (
                'id' => 2516,
                'role_id' => 2,
                'permission_id' => 4,
                'route_name' => 'role.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            158 => 
            array (
                'id' => 2517,
                'role_id' => 2,
                'permission_id' => 216,
                'route_name' => 'role.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            159 => 
            array (
                'id' => 2518,
                'role_id' => 2,
                'permission_id' => 217,
                'route_name' => 'role.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            160 => 
            array (
                'id' => 2519,
                'role_id' => 2,
                'permission_id' => 215,
                'route_name' => 'role.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            161 => 
            array (
                'id' => 2520,
                'role_id' => 2,
                'permission_id' => 14,
                'route_name' => 'user.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            162 => 
            array (
                'id' => 2521,
                'role_id' => 2,
                'permission_id' => 15,
                'route_name' => 'user.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            163 => 
            array (
                'id' => 2522,
                'role_id' => 2,
                'permission_id' => 117,
                'route_name' => 'user.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            164 => 
            array (
                'id' => 2523,
                'role_id' => 2,
                'permission_id' => 16,
                'route_name' => 'user.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            165 => 
            array (
                'id' => 2524,
                'role_id' => 2,
                'permission_id' => 213,
                'route_name' => 'user.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            166 => 
            array (
                'id' => 2525,
                'role_id' => 2,
                'permission_id' => 214,
                'route_name' => 'user.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            167 => 
            array (
                'id' => 2526,
                'role_id' => 2,
                'permission_id' => 212,
                'route_name' => 'user.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            168 => 
            array (
                'id' => 2527,
                'role_id' => 2,
                'permission_id' => 114,
                'route_name' => 'activity_log.show',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            169 => 
            array (
                'id' => 2528,
                'role_id' => 2,
                'permission_id' => 234,
                'route_name' => 'activity_log.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            170 => 
            array (
                'id' => 2529,
                'role_id' => 2,
                'permission_id' => 235,
                'route_name' => 'activity_log.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            171 => 
            array (
                'id' => 2530,
                'role_id' => 2,
                'permission_id' => 233,
                'route_name' => 'activity_log.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            172 => 
            array (
                'id' => 2531,
                'role_id' => 2,
                'permission_id' => 67,
                'route_name' => 'content.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            173 => 
            array (
                'id' => 2532,
                'role_id' => 2,
                'permission_id' => 237,
                'route_name' => 'content.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            174 => 
            array (
                'id' => 2533,
                'role_id' => 2,
                'permission_id' => 238,
                'route_name' => 'content.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            175 => 
            array (
                'id' => 2534,
                'role_id' => 2,
                'permission_id' => 236,
                'route_name' => 'content.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            176 => 
            array (
                'id' => 2535,
                'role_id' => 2,
                'permission_id' => 199,
                'route_name' => 'employee.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            177 => 
            array (
                'id' => 2536,
                'role_id' => 2,
                'permission_id' => 200,
                'route_name' => 'employee.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            178 => 
            array (
                'id' => 2537,
                'role_id' => 2,
                'permission_id' => 202,
                'route_name' => 'employee.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            179 => 
            array (
                'id' => 2538,
                'role_id' => 2,
                'permission_id' => 204,
                'route_name' => 'employee.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            180 => 
            array (
                'id' => 2539,
                'role_id' => 2,
                'permission_id' => 205,
                'route_name' => 'employee.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            181 => 
            array (
                'id' => 2540,
                'role_id' => 2,
                'permission_id' => 203,
                'route_name' => 'employee.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
        ));
        
        
    }
}