<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_permissions')->delete();
        
        \DB::table('user_permissions')->insert(array (
            0 => 
            array (
                'id' => 4355,
                'user_id' => 1,
                'permission_id' => 1,
                'route_name' => 'dashboard',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            1 => 
            array (
                'id' => 4356,
                'user_id' => 1,
                'permission_id' => 2,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            2 => 
            array (
                'id' => 4357,
                'user_id' => 1,
                'permission_id' => 3,
                'route_name' => 'menu.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            3 => 
            array (
                'id' => 4358,
                'user_id' => 1,
                'permission_id' => 4,
                'route_name' => 'menu_action.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            4 => 
            array (
                'id' => 4359,
                'user_id' => 1,
                'permission_id' => 5,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            5 => 
            array (
                'id' => 4360,
                'user_id' => 1,
                'permission_id' => 6,
                'route_name' => 'division.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            6 => 
            array (
                'id' => 4361,
                'user_id' => 1,
                'permission_id' => 30,
                'route_name' => 'district.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            7 => 
            array (
                'id' => 4362,
                'user_id' => 1,
                'permission_id' => 31,
                'route_name' => 'thana.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            8 => 
            array (
                'id' => 4363,
                'user_id' => 1,
                'permission_id' => 33,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            9 => 
            array (
                'id' => 4364,
                'user_id' => 1,
                'permission_id' => 63,
                'route_name' => 'fire_station_type.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            10 => 
            array (
                'id' => 4365,
                'user_id' => 1,
                'permission_id' => 49,
                'route_name' => 'fire_station.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            11 => 
            array (
                'id' => 4366,
                'user_id' => 1,
                'permission_id' => 75,
                'route_name' => 'country.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            12 => 
            array (
                'id' => 4367,
                'user_id' => 1,
                'permission_id' => 95,
                'route_name' => 'designation.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            13 => 
            array (
                'id' => 4368,
                'user_id' => 1,
                'permission_id' => 10,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            14 => 
            array (
                'id' => 4369,
                'user_id' => 1,
                'permission_id' => 45,
                'route_name' => 'role.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            15 => 
            array (
                'id' => 4370,
                'user_id' => 1,
                'permission_id' => 44,
                'route_name' => 'user.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            16 => 
            array (
                'id' => 4371,
                'user_id' => 1,
                'permission_id' => 74,
                'route_name' => 'activity_log.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            17 => 
            array (
                'id' => 4372,
                'user_id' => 1,
                'permission_id' => 25,
                'route_name' => 'content.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            18 => 
            array (
                'id' => 4373,
                'user_id' => 1,
                'permission_id' => 94,
                'route_name' => 'employee.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            19 => 
            array (
                'id' => 4374,
                'user_id' => 1,
                'permission_id' => 1,
                'route_name' => 'menu.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            20 => 
            array (
                'id' => 4375,
                'user_id' => 1,
                'permission_id' => 243,
                'route_name' => 'menu.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            21 => 
            array (
                'id' => 4376,
                'user_id' => 1,
                'permission_id' => 245,
                'route_name' => 'menu_action.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            22 => 
            array (
                'id' => 4377,
                'user_id' => 1,
                'permission_id' => 246,
                'route_name' => 'menu_action.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            23 => 
            array (
                'id' => 4378,
                'user_id' => 1,
                'permission_id' => 244,
                'route_name' => 'menu_action.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            24 => 
            array (
                'id' => 4379,
                'user_id' => 1,
                'permission_id' => 11,
                'route_name' => 'division.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            25 => 
            array (
                'id' => 4380,
                'user_id' => 1,
                'permission_id' => 12,
                'route_name' => 'division.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            26 => 
            array (
                'id' => 4381,
                'user_id' => 1,
                'permission_id' => 13,
                'route_name' => 'division.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            27 => 
            array (
                'id' => 4382,
                'user_id' => 1,
                'permission_id' => 219,
                'route_name' => 'division.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            28 => 
            array (
                'id' => 4383,
                'user_id' => 1,
                'permission_id' => 220,
                'route_name' => 'division.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            29 => 
            array (
                'id' => 4384,
                'user_id' => 1,
                'permission_id' => 218,
                'route_name' => 'division.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            30 => 
            array (
                'id' => 4385,
                'user_id' => 1,
                'permission_id' => 32,
                'route_name' => 'district.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            31 => 
            array (
                'id' => 4386,
                'user_id' => 1,
                'permission_id' => 33,
                'route_name' => 'district.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            32 => 
            array (
                'id' => 4387,
                'user_id' => 1,
                'permission_id' => 34,
                'route_name' => 'district.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            33 => 
            array (
                'id' => 4388,
                'user_id' => 1,
                'permission_id' => 222,
                'route_name' => 'district.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            34 => 
            array (
                'id' => 4389,
                'user_id' => 1,
                'permission_id' => 223,
                'route_name' => 'district.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            35 => 
            array (
                'id' => 4390,
                'user_id' => 1,
                'permission_id' => 221,
                'route_name' => 'district.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            36 => 
            array (
                'id' => 4391,
                'user_id' => 1,
                'permission_id' => 35,
                'route_name' => 'thana.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            37 => 
            array (
                'id' => 4392,
                'user_id' => 1,
                'permission_id' => 36,
                'route_name' => 'thana.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            38 => 
            array (
                'id' => 4393,
                'user_id' => 1,
                'permission_id' => 37,
                'route_name' => 'thana.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            39 => 
            array (
                'id' => 4394,
                'user_id' => 1,
                'permission_id' => 225,
                'route_name' => 'thana.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            40 => 
            array (
                'id' => 4395,
                'user_id' => 1,
                'permission_id' => 226,
                'route_name' => 'thana.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            41 => 
            array (
                'id' => 4396,
                'user_id' => 1,
                'permission_id' => 224,
                'route_name' => 'thana.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            42 => 
            array (
                'id' => 4397,
                'user_id' => 1,
                'permission_id' => 41,
                'route_name' => 'fire_station_type.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            43 => 
            array (
                'id' => 4398,
                'user_id' => 1,
                'permission_id' => 42,
                'route_name' => 'fire_station_type.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            44 => 
            array (
                'id' => 4399,
                'user_id' => 1,
                'permission_id' => 43,
                'route_name' => 'fire_station_type.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            45 => 
            array (
                'id' => 4400,
                'user_id' => 1,
                'permission_id' => 228,
                'route_name' => 'fire_station_type.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            46 => 
            array (
                'id' => 4401,
                'user_id' => 1,
                'permission_id' => 229,
                'route_name' => 'fire_station_type.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            47 => 
            array (
                'id' => 4402,
                'user_id' => 1,
                'permission_id' => 227,
                'route_name' => 'fire_station_type.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            48 => 
            array (
                'id' => 4403,
                'user_id' => 1,
                'permission_id' => 44,
                'route_name' => 'fire_station.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            49 => 
            array (
                'id' => 4404,
                'user_id' => 1,
                'permission_id' => 45,
                'route_name' => 'fire_station.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            50 => 
            array (
                'id' => 4405,
                'user_id' => 1,
                'permission_id' => 46,
                'route_name' => 'fire_station.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            51 => 
            array (
                'id' => 4406,
                'user_id' => 1,
                'permission_id' => 231,
                'route_name' => 'fire_station.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            52 => 
            array (
                'id' => 4407,
                'user_id' => 1,
                'permission_id' => 232,
                'route_name' => 'fire_station.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            53 => 
            array (
                'id' => 4408,
                'user_id' => 1,
                'permission_id' => 230,
                'route_name' => 'fire_station.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            54 => 
            array (
                'id' => 4409,
                'user_id' => 1,
                'permission_id' => 118,
                'route_name' => 'country.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            55 => 
            array (
                'id' => 4410,
                'user_id' => 1,
                'permission_id' => 119,
                'route_name' => 'country.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            56 => 
            array (
                'id' => 4411,
                'user_id' => 1,
                'permission_id' => 120,
                'route_name' => 'country.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            57 => 
            array (
                'id' => 4412,
                'user_id' => 1,
                'permission_id' => 140,
                'route_name' => 'country.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            58 => 
            array (
                'id' => 4413,
                'user_id' => 1,
                'permission_id' => 133,
                'route_name' => 'country.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            59 => 
            array (
                'id' => 4414,
                'user_id' => 1,
                'permission_id' => 132,
                'route_name' => 'country.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            60 => 
            array (
                'id' => 4415,
                'user_id' => 1,
                'permission_id' => 206,
                'route_name' => 'designation.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            61 => 
            array (
                'id' => 4416,
                'user_id' => 1,
                'permission_id' => 207,
                'route_name' => 'designation.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            62 => 
            array (
                'id' => 4417,
                'user_id' => 1,
                'permission_id' => 208,
                'route_name' => 'designation.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            63 => 
            array (
                'id' => 4418,
                'user_id' => 1,
                'permission_id' => 210,
                'route_name' => 'designation.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            64 => 
            array (
                'id' => 4419,
                'user_id' => 1,
                'permission_id' => 211,
                'route_name' => 'designation.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            65 => 
            array (
                'id' => 4420,
                'user_id' => 1,
                'permission_id' => 209,
                'route_name' => 'designation.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            66 => 
            array (
                'id' => 4421,
                'user_id' => 1,
                'permission_id' => 2,
                'route_name' => 'role.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            67 => 
            array (
                'id' => 4422,
                'user_id' => 1,
                'permission_id' => 3,
                'route_name' => 'role.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            68 => 
            array (
                'id' => 4423,
                'user_id' => 1,
                'permission_id' => 69,
                'route_name' => 'role.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            69 => 
            array (
                'id' => 4424,
                'user_id' => 1,
                'permission_id' => 4,
                'route_name' => 'role.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            70 => 
            array (
                'id' => 4425,
                'user_id' => 1,
                'permission_id' => 216,
                'route_name' => 'role.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            71 => 
            array (
                'id' => 4426,
                'user_id' => 1,
                'permission_id' => 217,
                'route_name' => 'role.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            72 => 
            array (
                'id' => 4427,
                'user_id' => 1,
                'permission_id' => 215,
                'route_name' => 'role.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            73 => 
            array (
                'id' => 4428,
                'user_id' => 1,
                'permission_id' => 14,
                'route_name' => 'user.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            74 => 
            array (
                'id' => 4429,
                'user_id' => 1,
                'permission_id' => 15,
                'route_name' => 'user.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            75 => 
            array (
                'id' => 4430,
                'user_id' => 1,
                'permission_id' => 117,
                'route_name' => 'user.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            76 => 
            array (
                'id' => 4431,
                'user_id' => 1,
                'permission_id' => 16,
                'route_name' => 'user.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            77 => 
            array (
                'id' => 4432,
                'user_id' => 1,
                'permission_id' => 213,
                'route_name' => 'user.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            78 => 
            array (
                'id' => 4433,
                'user_id' => 1,
                'permission_id' => 214,
                'route_name' => 'user.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            79 => 
            array (
                'id' => 4434,
                'user_id' => 1,
                'permission_id' => 212,
                'route_name' => 'user.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            80 => 
            array (
                'id' => 4435,
                'user_id' => 1,
                'permission_id' => 114,
                'route_name' => 'activity_log.show',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            81 => 
            array (
                'id' => 4436,
                'user_id' => 1,
                'permission_id' => 234,
                'route_name' => 'activity_log.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            82 => 
            array (
                'id' => 4437,
                'user_id' => 1,
                'permission_id' => 235,
                'route_name' => 'activity_log.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            83 => 
            array (
                'id' => 4438,
                'user_id' => 1,
                'permission_id' => 233,
                'route_name' => 'activity_log.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            84 => 
            array (
                'id' => 4439,
                'user_id' => 1,
                'permission_id' => 66,
                'route_name' => 'content.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            85 => 
            array (
                'id' => 4440,
                'user_id' => 1,
                'permission_id' => 67,
                'route_name' => 'content.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            86 => 
            array (
                'id' => 4441,
                'user_id' => 1,
                'permission_id' => 68,
                'route_name' => 'content.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            87 => 
            array (
                'id' => 4442,
                'user_id' => 1,
                'permission_id' => 237,
                'route_name' => 'content.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            88 => 
            array (
                'id' => 4443,
                'user_id' => 1,
                'permission_id' => 238,
                'route_name' => 'content.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            89 => 
            array (
                'id' => 4444,
                'user_id' => 1,
                'permission_id' => 236,
                'route_name' => 'content.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            90 => 
            array (
                'id' => 4445,
                'user_id' => 1,
                'permission_id' => 199,
                'route_name' => 'employee.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            91 => 
            array (
                'id' => 4446,
                'user_id' => 1,
                'permission_id' => 200,
                'route_name' => 'employee.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            92 => 
            array (
                'id' => 4447,
                'user_id' => 1,
                'permission_id' => 202,
                'route_name' => 'employee.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            93 => 
            array (
                'id' => 4448,
                'user_id' => 1,
                'permission_id' => 204,
                'route_name' => 'employee.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            94 => 
            array (
                'id' => 4449,
                'user_id' => 1,
                'permission_id' => 205,
                'route_name' => 'employee.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            95 => 
            array (
                'id' => 4450,
                'user_id' => 1,
                'permission_id' => 203,
                'route_name' => 'employee.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:03',
                'updated_at' => '2021-10-21 11:20:03',
            ),
            96 => 
            array (
                'id' => 4451,
                'user_id' => 2,
                'permission_id' => 1,
                'route_name' => 'dashboard',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            97 => 
            array (
                'id' => 4452,
                'user_id' => 2,
                'permission_id' => 5,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            98 => 
            array (
                'id' => 4453,
                'user_id' => 2,
                'permission_id' => 6,
                'route_name' => 'division.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            99 => 
            array (
                'id' => 4454,
                'user_id' => 2,
                'permission_id' => 30,
                'route_name' => 'district.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            100 => 
            array (
                'id' => 4455,
                'user_id' => 2,
                'permission_id' => 31,
                'route_name' => 'thana.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            101 => 
            array (
                'id' => 4456,
                'user_id' => 2,
                'permission_id' => 33,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            102 => 
            array (
                'id' => 4457,
                'user_id' => 2,
                'permission_id' => 63,
                'route_name' => 'fire_station_type.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            103 => 
            array (
                'id' => 4458,
                'user_id' => 2,
                'permission_id' => 49,
                'route_name' => 'fire_station.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            104 => 
            array (
                'id' => 4459,
                'user_id' => 2,
                'permission_id' => 75,
                'route_name' => 'country.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            105 => 
            array (
                'id' => 4460,
                'user_id' => 2,
                'permission_id' => 95,
                'route_name' => 'designation.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            106 => 
            array (
                'id' => 4461,
                'user_id' => 2,
                'permission_id' => 10,
                'route_name' => NULL,
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            107 => 
            array (
                'id' => 4462,
                'user_id' => 2,
                'permission_id' => 45,
                'route_name' => 'role.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            108 => 
            array (
                'id' => 4463,
                'user_id' => 2,
                'permission_id' => 44,
                'route_name' => 'user.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            109 => 
            array (
                'id' => 4464,
                'user_id' => 2,
                'permission_id' => 74,
                'route_name' => 'activity_log.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            110 => 
            array (
                'id' => 4465,
                'user_id' => 2,
                'permission_id' => 25,
                'route_name' => 'content.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            111 => 
            array (
                'id' => 4466,
                'user_id' => 2,
                'permission_id' => 94,
                'route_name' => 'employee.index',
                'permission_type' => 'menu',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            112 => 
            array (
                'id' => 4467,
                'user_id' => 2,
                'permission_id' => 11,
                'route_name' => 'division.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            113 => 
            array (
                'id' => 4468,
                'user_id' => 2,
                'permission_id' => 12,
                'route_name' => 'division.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            114 => 
            array (
                'id' => 4469,
                'user_id' => 2,
                'permission_id' => 13,
                'route_name' => 'division.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            115 => 
            array (
                'id' => 4470,
                'user_id' => 2,
                'permission_id' => 219,
                'route_name' => 'division.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            116 => 
            array (
                'id' => 4471,
                'user_id' => 2,
                'permission_id' => 220,
                'route_name' => 'division.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            117 => 
            array (
                'id' => 4472,
                'user_id' => 2,
                'permission_id' => 218,
                'route_name' => 'division.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            118 => 
            array (
                'id' => 4473,
                'user_id' => 2,
                'permission_id' => 32,
                'route_name' => 'district.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            119 => 
            array (
                'id' => 4474,
                'user_id' => 2,
                'permission_id' => 33,
                'route_name' => 'district.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            120 => 
            array (
                'id' => 4475,
                'user_id' => 2,
                'permission_id' => 34,
                'route_name' => 'district.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            121 => 
            array (
                'id' => 4476,
                'user_id' => 2,
                'permission_id' => 222,
                'route_name' => 'district.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            122 => 
            array (
                'id' => 4477,
                'user_id' => 2,
                'permission_id' => 223,
                'route_name' => 'district.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            123 => 
            array (
                'id' => 4478,
                'user_id' => 2,
                'permission_id' => 221,
                'route_name' => 'district.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            124 => 
            array (
                'id' => 4479,
                'user_id' => 2,
                'permission_id' => 35,
                'route_name' => 'thana.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            125 => 
            array (
                'id' => 4480,
                'user_id' => 2,
                'permission_id' => 36,
                'route_name' => 'thana.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            126 => 
            array (
                'id' => 4481,
                'user_id' => 2,
                'permission_id' => 37,
                'route_name' => 'thana.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            127 => 
            array (
                'id' => 4482,
                'user_id' => 2,
                'permission_id' => 225,
                'route_name' => 'thana.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            128 => 
            array (
                'id' => 4483,
                'user_id' => 2,
                'permission_id' => 226,
                'route_name' => 'thana.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            129 => 
            array (
                'id' => 4484,
                'user_id' => 2,
                'permission_id' => 224,
                'route_name' => 'thana.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            130 => 
            array (
                'id' => 4485,
                'user_id' => 2,
                'permission_id' => 41,
                'route_name' => 'fire_station_type.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            131 => 
            array (
                'id' => 4486,
                'user_id' => 2,
                'permission_id' => 42,
                'route_name' => 'fire_station_type.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            132 => 
            array (
                'id' => 4487,
                'user_id' => 2,
                'permission_id' => 43,
                'route_name' => 'fire_station_type.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            133 => 
            array (
                'id' => 4488,
                'user_id' => 2,
                'permission_id' => 228,
                'route_name' => 'fire_station_type.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            134 => 
            array (
                'id' => 4489,
                'user_id' => 2,
                'permission_id' => 229,
                'route_name' => 'fire_station_type.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            135 => 
            array (
                'id' => 4490,
                'user_id' => 2,
                'permission_id' => 227,
                'route_name' => 'fire_station_type.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            136 => 
            array (
                'id' => 4491,
                'user_id' => 2,
                'permission_id' => 44,
                'route_name' => 'fire_station.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            137 => 
            array (
                'id' => 4492,
                'user_id' => 2,
                'permission_id' => 45,
                'route_name' => 'fire_station.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            138 => 
            array (
                'id' => 4493,
                'user_id' => 2,
                'permission_id' => 46,
                'route_name' => 'fire_station.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            139 => 
            array (
                'id' => 4494,
                'user_id' => 2,
                'permission_id' => 231,
                'route_name' => 'fire_station.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            140 => 
            array (
                'id' => 4495,
                'user_id' => 2,
                'permission_id' => 232,
                'route_name' => 'fire_station.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            141 => 
            array (
                'id' => 4496,
                'user_id' => 2,
                'permission_id' => 230,
                'route_name' => 'fire_station.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            142 => 
            array (
                'id' => 4497,
                'user_id' => 2,
                'permission_id' => 118,
                'route_name' => 'country.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            143 => 
            array (
                'id' => 4498,
                'user_id' => 2,
                'permission_id' => 119,
                'route_name' => 'country.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            144 => 
            array (
                'id' => 4499,
                'user_id' => 2,
                'permission_id' => 120,
                'route_name' => 'country.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            145 => 
            array (
                'id' => 4500,
                'user_id' => 2,
                'permission_id' => 140,
                'route_name' => 'country.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            146 => 
            array (
                'id' => 4501,
                'user_id' => 2,
                'permission_id' => 133,
                'route_name' => 'country.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            147 => 
            array (
                'id' => 4502,
                'user_id' => 2,
                'permission_id' => 132,
                'route_name' => 'country.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            148 => 
            array (
                'id' => 4503,
                'user_id' => 2,
                'permission_id' => 206,
                'route_name' => 'designation.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            149 => 
            array (
                'id' => 4504,
                'user_id' => 2,
                'permission_id' => 207,
                'route_name' => 'designation.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            150 => 
            array (
                'id' => 4505,
                'user_id' => 2,
                'permission_id' => 208,
                'route_name' => 'designation.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            151 => 
            array (
                'id' => 4506,
                'user_id' => 2,
                'permission_id' => 210,
                'route_name' => 'designation.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            152 => 
            array (
                'id' => 4507,
                'user_id' => 2,
                'permission_id' => 211,
                'route_name' => 'designation.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            153 => 
            array (
                'id' => 4508,
                'user_id' => 2,
                'permission_id' => 209,
                'route_name' => 'designation.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            154 => 
            array (
                'id' => 4509,
                'user_id' => 2,
                'permission_id' => 2,
                'route_name' => 'role.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            155 => 
            array (
                'id' => 4510,
                'user_id' => 2,
                'permission_id' => 3,
                'route_name' => 'role.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            156 => 
            array (
                'id' => 4511,
                'user_id' => 2,
                'permission_id' => 69,
                'route_name' => 'role.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            157 => 
            array (
                'id' => 4512,
                'user_id' => 2,
                'permission_id' => 4,
                'route_name' => 'role.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            158 => 
            array (
                'id' => 4513,
                'user_id' => 2,
                'permission_id' => 216,
                'route_name' => 'role.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            159 => 
            array (
                'id' => 4514,
                'user_id' => 2,
                'permission_id' => 217,
                'route_name' => 'role.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            160 => 
            array (
                'id' => 4515,
                'user_id' => 2,
                'permission_id' => 215,
                'route_name' => 'role.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            161 => 
            array (
                'id' => 4516,
                'user_id' => 2,
                'permission_id' => 14,
                'route_name' => 'user.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            162 => 
            array (
                'id' => 4517,
                'user_id' => 2,
                'permission_id' => 15,
                'route_name' => 'user.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            163 => 
            array (
                'id' => 4518,
                'user_id' => 2,
                'permission_id' => 117,
                'route_name' => 'user.permission',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            164 => 
            array (
                'id' => 4519,
                'user_id' => 2,
                'permission_id' => 16,
                'route_name' => 'user.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            165 => 
            array (
                'id' => 4520,
                'user_id' => 2,
                'permission_id' => 213,
                'route_name' => 'user.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            166 => 
            array (
                'id' => 4521,
                'user_id' => 2,
                'permission_id' => 214,
                'route_name' => 'user.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            167 => 
            array (
                'id' => 4522,
                'user_id' => 2,
                'permission_id' => 212,
                'route_name' => 'user.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            168 => 
            array (
                'id' => 4523,
                'user_id' => 2,
                'permission_id' => 114,
                'route_name' => 'activity_log.show',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            169 => 
            array (
                'id' => 4524,
                'user_id' => 2,
                'permission_id' => 234,
                'route_name' => 'activity_log.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            170 => 
            array (
                'id' => 4525,
                'user_id' => 2,
                'permission_id' => 235,
                'route_name' => 'activity_log.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            171 => 
            array (
                'id' => 4526,
                'user_id' => 2,
                'permission_id' => 233,
                'route_name' => 'activity_log.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            172 => 
            array (
                'id' => 4527,
                'user_id' => 2,
                'permission_id' => 67,
                'route_name' => 'content.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            173 => 
            array (
                'id' => 4528,
                'user_id' => 2,
                'permission_id' => 237,
                'route_name' => 'content.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            174 => 
            array (
                'id' => 4529,
                'user_id' => 2,
                'permission_id' => 238,
                'route_name' => 'content.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            175 => 
            array (
                'id' => 4530,
                'user_id' => 2,
                'permission_id' => 236,
                'route_name' => 'content.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            176 => 
            array (
                'id' => 4531,
                'user_id' => 2,
                'permission_id' => 199,
                'route_name' => 'employee.create',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            177 => 
            array (
                'id' => 4532,
                'user_id' => 2,
                'permission_id' => 200,
                'route_name' => 'employee.edit',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            178 => 
            array (
                'id' => 4533,
                'user_id' => 2,
                'permission_id' => 202,
                'route_name' => 'employee.destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            179 => 
            array (
                'id' => 4534,
                'user_id' => 2,
                'permission_id' => 204,
                'route_name' => 'employee.restore',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            180 => 
            array (
                'id' => 4535,
                'user_id' => 2,
                'permission_id' => 205,
                'route_name' => 'employee.force_destroy',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
            181 => 
            array (
                'id' => 4536,
                'user_id' => 2,
                'permission_id' => 203,
                'route_name' => 'employee.deleted_list',
                'permission_type' => 'menu_action',
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2021-10-21 11:20:12',
                'updated_at' => '2021-10-21 11:20:12',
            ),
        ));
        
        
    }
}