<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserMenuActionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_menu_actions')->delete();
        
        \DB::table('user_menu_actions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 3,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'menu.create',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-27 16:44:07',
                'updated_at' => '2021-09-07 15:30:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 45,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'role.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-27 17:26:04',
                'updated_at' => '2021-10-21 11:08:18',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 45,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'role.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-27 17:26:36',
                'updated_at' => '2021-10-21 11:08:33',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 45,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'role.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-27 17:27:25',
                'updated_at' => '2021-10-21 11:09:24',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 11,
                'menu_id' => 6,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'division.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:20:32',
                'updated_at' => '2021-10-21 10:41:15',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 12,
                'menu_id' => 6,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'division.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:20:57',
                'updated_at' => '2021-10-21 10:41:35',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 13,
                'menu_id' => 6,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'division.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:21:22',
                'updated_at' => '2021-10-21 10:57:52',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 14,
                'menu_id' => 44,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'user.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:41:43',
                'updated_at' => '2021-10-21 11:15:49',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                'menu_id' => 44,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'user.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:42:12',
                'updated_at' => '2021-10-21 11:16:05',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 16,
                'menu_id' => 44,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'user.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-02-28 10:42:44',
                'updated_at' => '2021-10-21 11:17:15',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 32,
                'menu_id' => 30,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'district.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 12:27:05',
                'updated_at' => '2021-10-21 11:02:10',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 33,
                'menu_id' => 30,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'district.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 12:27:29',
                'updated_at' => '2021-10-21 11:02:19',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 34,
                'menu_id' => 30,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'district.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 12:27:48',
                'updated_at' => '2021-10-21 11:02:39',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 35,
                'menu_id' => 31,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'thana.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 14:49:02',
                'updated_at' => '2021-10-21 10:58:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 36,
                'menu_id' => 31,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'thana.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 14:49:23',
                'updated_at' => '2021-10-21 10:59:11',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 37,
                'menu_id' => 31,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'thana.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 14:49:41',
                'updated_at' => '2021-10-21 10:59:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 41,
                'menu_id' => 63,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'fire_station_type.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 17:50:43',
                'updated_at' => '2021-10-21 11:04:40',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 42,
                'menu_id' => 63,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'fire_station_type.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 17:51:02',
                'updated_at' => '2021-10-21 11:05:04',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 43,
                'menu_id' => 63,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'fire_station_type.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 17:51:56',
                'updated_at' => '2021-10-21 11:05:30',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 44,
                'menu_id' => 49,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'fire_station.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 18:15:18',
                'updated_at' => '2021-10-21 11:06:17',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 45,
                'menu_id' => 49,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'fire_station.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 18:15:33',
                'updated_at' => '2021-10-21 11:06:32',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 46,
                'menu_id' => 49,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'fire_station.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-01 18:15:55',
                'updated_at' => '2021-10-21 11:06:49',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 66,
                'menu_id' => 25,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'content.create',
                'type' => 'action',
                'slug' => 'add',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-15 10:09:01',
                'updated_at' => '2021-10-17 14:22:46',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 67,
                'menu_id' => 25,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'content.edit',
                'type' => 'action',
                'slug' => 'edit',
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-15 10:09:45',
                'updated_at' => '2021-10-17 14:23:08',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 68,
                'menu_id' => 25,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'content.destroy',
                'type' => 'action',
                'slug' => 'delete',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 1,
                'status' => 1,
                'created_at' => '2021-03-15 10:10:19',
                'updated_at' => '2021-10-17 14:23:50',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 69,
                'menu_id' => 45,
                'menu_action_id' => 5,
                'parent_id' => NULL,
                'name' => 'Permission',
                'bn_name' => 'অনুমতি',
                'route_name' => 'role.permission',
                'type' => 'action',
                'slug' => 'permission',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-03-16 16:30:46',
                'updated_at' => '2021-10-21 11:09:01',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 114,
                'menu_id' => 74,
                'menu_action_id' => 4,
                'parent_id' => NULL,
                'name' => 'View',
                'bn_name' => 'বিস্তারিত',
                'route_name' => 'activity_log.show',
                'type' => 'action',
                'slug' => 'view',
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-06-17 17:18:50',
                'updated_at' => '2021-10-21 11:18:09',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 117,
                'menu_id' => 44,
                'menu_action_id' => 5,
                'parent_id' => NULL,
                'name' => 'Permission',
                'bn_name' => 'অনুমতি',
                'route_name' => 'user.permission',
                'type' => 'action',
                'slug' => 'permission',
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-06-30 12:32:04',
                'updated_at' => '2021-10-21 11:16:36',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 118,
                'menu_id' => 75,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'country.create',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-03 18:59:54',
                'updated_at' => '2021-07-03 20:45:53',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 119,
                'menu_id' => 75,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'country.edit',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-03 20:09:21',
                'updated_at' => '2021-07-03 20:43:15',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 120,
                'menu_id' => 75,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'country.destroy',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-03 20:18:54',
                'updated_at' => '2021-07-03 20:43:20',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 132,
                'menu_id' => 75,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'country.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-08 15:27:20',
                'updated_at' => '2021-08-21 11:09:50',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 133,
                'menu_id' => 75,
                'menu_action_id' => 3,
                'parent_id' => 132,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'country.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-08 17:25:36',
                'updated_at' => '2021-07-12 17:57:31',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 140,
                'menu_id' => 75,
                'menu_action_id' => 10,
                'parent_id' => 132,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'country.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-07-12 17:58:35',
                'updated_at' => '2021-07-12 17:58:35',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 199,
                'menu_id' => 94,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'employee.create',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:46:30',
                'updated_at' => '2021-08-02 14:46:30',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 200,
                'menu_id' => 94,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'employee.edit',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:47:04',
                'updated_at' => '2021-08-02 14:47:04',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 201,
                'menu_id' => 94,
                'menu_action_id' => 4,
                'parent_id' => NULL,
                'name' => 'View',
                'bn_name' => 'বিস্তারিত',
                'route_name' => 'employee.show',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 0,
                'created_at' => '2021-08-02 14:47:55',
                'updated_at' => '2021-08-18 11:03:26',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 202,
                'menu_id' => 94,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'employee.destroy',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:48:25',
                'updated_at' => '2021-08-02 14:48:25',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 203,
                'menu_id' => 94,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'employee.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:49:14',
                'updated_at' => '2021-08-03 11:23:58',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 204,
                'menu_id' => 94,
                'menu_action_id' => 10,
                'parent_id' => 203,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'employee.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:50:06',
                'updated_at' => '2021-08-02 14:50:06',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 205,
                'menu_id' => 94,
                'menu_action_id' => 3,
                'parent_id' => 203,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'employee.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:51:36',
                'updated_at' => '2021-08-02 14:51:36',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 206,
                'menu_id' => 95,
                'menu_action_id' => 1,
                'parent_id' => NULL,
                'name' => 'Add',
                'bn_name' => 'সংযোজন',
                'route_name' => 'designation.create',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:46:30',
                'updated_at' => '2021-10-18 11:07:56',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 207,
                'menu_id' => 95,
                'menu_action_id' => 2,
                'parent_id' => NULL,
                'name' => 'Edit',
                'bn_name' => 'পরিমার্জন',
                'route_name' => 'designation.edit',
                'type' => 'action',
                'slug' => NULL,
                'class' => 'modal_lg_button',
                'order_by' => 2,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:47:04',
                'updated_at' => '2021-08-02 14:47:04',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 208,
                'menu_id' => 95,
                'menu_action_id' => 3,
                'parent_id' => NULL,
                'name' => 'Delete',
                'bn_name' => 'ডিলেট',
                'route_name' => 'designation.destroy',
                'type' => 'action',
                'slug' => NULL,
                'class' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:48:25',
                'updated_at' => '2021-08-02 14:48:25',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 209,
                'menu_id' => 95,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'designation.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:49:14',
                'updated_at' => '2021-08-03 11:33:51',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 210,
                'menu_id' => 95,
                'menu_action_id' => 10,
                'parent_id' => 209,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'designation.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:50:06',
                'updated_at' => '2021-08-02 14:50:06',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 211,
                'menu_id' => 95,
                'menu_action_id' => 3,
                'parent_id' => 209,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'designation.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-08-02 14:51:36',
                'updated_at' => '2021-08-02 14:51:36',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 212,
                'menu_id' => 44,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'user.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 09:59:43',
                'updated_at' => '2021-10-17 09:59:43',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 213,
                'menu_id' => 44,
                'menu_action_id' => 10,
                'parent_id' => 212,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'user.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 10:01:57',
                'updated_at' => '2021-10-17 10:03:02',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 214,
                'menu_id' => 44,
                'menu_action_id' => 3,
                'parent_id' => 212,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'user.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 10:02:54',
                'updated_at' => '2021-10-17 10:02:54',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 215,
                'menu_id' => 45,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'role.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 11:36:54',
                'updated_at' => '2021-10-17 11:36:54',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 216,
                'menu_id' => 45,
                'menu_action_id' => 10,
                'parent_id' => 215,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'role.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 11:37:32',
                'updated_at' => '2021-10-17 11:37:32',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 217,
                'menu_id' => 45,
                'menu_action_id' => 3,
                'parent_id' => 215,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'role.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 11:38:37',
                'updated_at' => '2021-10-17 11:38:37',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 218,
                'menu_id' => 6,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'division.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:02:51',
                'updated_at' => '2021-10-17 12:02:51',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 219,
                'menu_id' => 6,
                'menu_action_id' => 10,
                'parent_id' => 218,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'division.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:03:52',
                'updated_at' => '2021-10-17 12:05:01',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 220,
                'menu_id' => 6,
                'menu_action_id' => 3,
                'parent_id' => 218,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'division.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:04:48',
                'updated_at' => '2021-10-17 12:04:48',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 221,
                'menu_id' => 30,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'district.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:11:26',
                'updated_at' => '2021-10-17 12:22:07',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 222,
                'menu_id' => 30,
                'menu_action_id' => 10,
                'parent_id' => 221,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'district.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:23:04',
                'updated_at' => '2021-10-17 12:23:04',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 223,
                'menu_id' => 30,
                'menu_action_id' => 3,
                'parent_id' => 221,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'district.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:23:55',
                'updated_at' => '2021-10-17 12:23:55',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 224,
                'menu_id' => 31,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'thana.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:29:59',
                'updated_at' => '2021-10-17 12:29:59',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 225,
                'menu_id' => 31,
                'menu_action_id' => 10,
                'parent_id' => 224,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'thana.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:33:59',
                'updated_at' => '2021-10-17 12:33:59',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 226,
                'menu_id' => 31,
                'menu_action_id' => 3,
                'parent_id' => 224,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'thana.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:34:48',
                'updated_at' => '2021-10-17 12:34:48',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 227,
                'menu_id' => 63,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'fire_station_type.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:36:22',
                'updated_at' => '2021-10-17 12:36:22',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 228,
                'menu_id' => 63,
                'menu_action_id' => 10,
                'parent_id' => 227,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'fire_station_type.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:36:54',
                'updated_at' => '2021-10-17 12:36:54',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 229,
                'menu_id' => 63,
                'menu_action_id' => 3,
                'parent_id' => 227,
                'name' => 'Permanent Delete',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'fire_station_type.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:37:39',
                'updated_at' => '2021-10-17 12:37:39',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 230,
                'menu_id' => 49,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'fire_station.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:40:17',
                'updated_at' => '2021-10-17 12:40:17',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 231,
                'menu_id' => 49,
                'menu_action_id' => 10,
                'parent_id' => 230,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'fire_station.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:40:17',
                'updated_at' => '2021-10-17 12:40:17',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 232,
                'menu_id' => 49,
                'menu_action_id' => 3,
                'parent_id' => 230,
                'name' => 'Delete Permanently',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'fire_station.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:40:17',
                'updated_at' => '2021-10-17 12:40:17',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 233,
                'menu_id' => 74,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'activity_log.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:43:44',
                'updated_at' => '2021-10-17 12:43:44',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 234,
                'menu_id' => 74,
                'menu_action_id' => 10,
                'parent_id' => 233,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'activity_log.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:43:44',
                'updated_at' => '2021-10-17 12:43:44',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 235,
                'menu_id' => 74,
                'menu_action_id' => 3,
                'parent_id' => 233,
                'name' => 'Delete Permanently',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'activity_log.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:43:44',
                'updated_at' => '2021-10-17 12:43:44',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 236,
                'menu_id' => 25,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'content.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:45:12',
                'updated_at' => '2021-10-17 12:45:12',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 237,
                'menu_id' => 25,
                'menu_action_id' => 10,
                'parent_id' => 236,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'content.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:45:12',
                'updated_at' => '2021-10-17 12:45:12',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 238,
                'menu_id' => 25,
                'menu_action_id' => 3,
                'parent_id' => 236,
                'name' => 'Delete Permanently',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'content.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 12:45:12',
                'updated_at' => '2021-10-17 12:45:12',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 243,
                'menu_id' => 3,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'menu.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 15:52:59',
                'updated_at' => '2021-10-17 15:52:59',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 244,
                'menu_id' => 4,
                'menu_action_id' => NULL,
                'parent_id' => NULL,
                'name' => 'Trash',
                'bn_name' => 'ডিলেটেড লিস্ট',
                'route_name' => 'menu_action.deleted_list',
                'type' => 'tab',
                'slug' => 'deleted_list',
                'class' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'show_in_table' => 0,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 16:51:13',
                'updated_at' => '2021-10-17 17:15:24',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 245,
                'menu_id' => 4,
                'menu_action_id' => 10,
                'parent_id' => 244,
                'name' => 'Restore',
                'bn_name' => 'পুনরুদ্ধার',
                'route_name' => 'menu_action.restore',
                'type' => 'action',
                'slug' => 'restore',
                'class' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 16:51:13',
                'updated_at' => '2021-10-17 17:15:32',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 246,
                'menu_id' => 4,
                'menu_action_id' => 3,
                'parent_id' => 244,
                'name' => 'Delete Permanently',
                'bn_name' => 'স্থায়ীভাবে ডিলেট',
                'route_name' => 'menu_action.force_destroy',
                'type' => 'action',
                'slug' => 'force_destroy',
                'class' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-17 16:51:13',
                'updated_at' => '2021-10-17 17:15:42',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 247,
                'menu_id' => 49,
                'menu_action_id' => 11,
                'parent_id' => NULL,
                'name' => 'Edit History',
                'bn_name' => 'পরিমার্জন বিবরণ',
                'route_name' => NULL,
                'type' => 'action',
                'slug' => 'edit_history',
                'class' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'show_in_table' => 1,
                'new_tab' => 0,
                'status' => 1,
                'created_at' => '2021-10-31 11:56:02',
                'updated_at' => '2021-11-01 15:38:02',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}